### ISSUE TITLE
Integrate with GHReleaseBridge.

### ISSUE THREAD

**Issue by antony-jr** [VioletGiraffe/github-releases-autoupdater#3]
Hey there I see your project aims to update any software which uses Github as a distribution platform ,
So here is an Interesting project that I created.
As You stated... 

> If you want to extend it to support OS X / Linux / whatever - be my guest. 

**GHReleaseBridge** (Built With Qt) does not just download a setup file and the start it. It goes like this , It reads the update configuration from a json file and then compares it with the upstream ( SemVer! ) , If the Upstream is the latest release then it downloads an archive(That you specified , With a WildCard) which has the changed files ( Only the changed files , Like your main executable , This avoids us to download the libs over and over again ) and then extracts that archive to the installation path you mention (Example: ./ , Which states the current folder where the main app is located  ) , The archive can be uploaded from **Travis-CI**. The new configuration will be written to the path you specify. Please do note that **GHReleaseBridge requires write permissions...**

**Its header only but can be compiled as a lib too.** , Here is the project site -> https://antony-jr.github.io/GHReleaseBridge
Github Project Page: https://github.com/antony-jr/GHReleaseBridge

**Comment by antony-jr** [comment]
I will send a PR soon , Thank You! Good Day!

**Comment by VioletGiraffe** [comment]
That's curious. I've found your project interesting, but didn't see a way how we could integrate our projects. Intrigued by your possible PR!
